[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
permissionless-vaults = "AYd3r7b9JYXmWdC8MqG6nCiaAgs3LqKA2xXEZ1gHNocK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/quellen/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
